name: gym_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter:
  google_fonts:
  provider: 
  table_calendar:
  shared_preferences:
  liquid_glass_bar: 
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0  
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  flutter_launcher_icons:
  build_runner: any
  isar_generator: ^3.1.0

flutter:
  uses-material-design: true
  assets: 
    - assets/exercises.json

flutter_icons:
  ios: true
  image_path: "assets/report.png"
  remove_alpha_ios: true
